//get action
export const GET_ROOM_PENDING = "GET_ROOM_PENDING";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_ERROR = "GET_ROOM_ERROR";

//post action
export const POST_ROOM_PENDING = "POST_ROOM_PENDING";
export const POST_ROOM_SUCCESS = "POST_ROOM_SUCCESS";
export const POST_ROOM_ERROR = "POST_ROOM_ERROR";

//DELETE action
export const DELETE_ROOM_PENDING = "DELETE_ROOM_PENDING";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_ERROR = "DELETE_ROOM_ERROR";

//UPDATA action
export const UPDATA_ROOM_PENDING = "UPDATA_ROOM_PENDING";
export const UPDATA_ROOM_SUCCESS = "UPDATA_ROOM_SUCCESS";
export const UPDATA_ROOM_ERROR = "UPDATA_ROOM_ERROR";